# Generated by Django 5.2.12 on 2026-06-02 07:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_chat_chatmessage_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_materials", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
