# Generated by Django 5.2.12 on 2026-06-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_material_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="subscription_type",
            field=models.CharField(
                choices=[("None", "None"), ("Pro", "Pro")],
                default="None",
                max_length=20,
            ),
        ),
    ]
